import { NavBar } from "@/components";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Carlos Cortés website generado con Next",
  description: "Generated by create next app",
};

export default function GeneralLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <>
      <NavBar />
      <main className="flex flex-col items-center p-24">
        <span className="text-lg">Hola mundo</span>
        {children}
      </main>
    </>


  );
}
